module Info exposing (..)

import Html exposing (Html)
import Html.Attributes as HA
import Html.Events as HE
import Messages exposing (Msg(..))
import Svg
import Svg.Attributes as SvgAttr


description : List (Html Msg)
description =
    [ "There is a list of some number of color values defined (3 by default). There are also 4 permutations defined, one for each quadrant (top left, top right, bottom left, and bottom right)."
    , "The image is generated by repeatedly applying permutations to the list of colors, which shuffles the order of the colors."
    , "For each quadrant of the image, the permutation associated with that quadrant is used to shuffle the initial list of colors. Then the quadrant is subdivided into 4 smaller quadrants, and the same process is applied again for each of those quadrants, but starting with the updated color order."
    , "This continues recursively for the number of levels specified in the configuration. After hitting that level, whatever color is currently first in the list is set as the value for that location in the image."
    , "In the configuration panel, you can adjust the permutations by clicking any of the blue dots, and swapping with another. You can also change the number of colors, and the value of each color in the initial list."
    ]
        |> List.map (\t -> Html.span [] [ Html.text t ])


backArrow : Html Msg
backArrow =
    Svg.svg
        [ SvgAttr.fill "#000000"
        , SvgAttr.width "20px"
        , SvgAttr.height "20px"
        , SvgAttr.viewBox "0 0 52 52"
        , HE.onClick (ShowHelpInfo False)
        , HA.style "cursor" "pointer"
        ]
        [ Svg.path
            [ SvgAttr.d "M50,24H6.83L27.41,3.41a2,2,0,0,0,0-2.82,2,2,0,0,0-2.82,0l-24,24a1.79,1.79,0,0,0-.25.31A1.19,1.19,0,0,0,.25,25c0,.07-.07.13-.1.2l-.06.2a.84.84,0,0,0,0,.17,2,2,0,0,0,0,.78.84.84,0,0,0,0,.17l.06.2c0,.07.07.13.1.2a1.19,1.19,0,0,0,.09.15,1.79,1.79,0,0,0,.25.31l24,24a2,2,0,1,0,2.82-2.82L6.83,28H50a2,2,0,0,0,0-4Z"
            ]
            []
        ]


helpView : Html Msg
helpView =
    Html.div
        [ HA.style "height" "100%"
        , HA.style "max-height" "100vh"
        , HA.style "flex-grow" "2"
        , HA.style "overflow-y" "scroll"
        , HA.style "background-color" "rgb(240, 240, 240)"
        , HA.style "position" "relative"
        ]
        [ Html.div
            [ HA.style "position" "absolute"
            , HA.style "top" "10px"
            , HA.style "left" "10px"
            , HA.style "display" "flex"
            , HA.style "gap" "10px"
            ]
            [ backArrow
            ]
        , Html.div
            [ HA.style "display" "flex"
            , HA.style "margin" "50px 10px"
            ]
            [ Html.div
                [ HA.style "display" "flex"
                , HA.style "flex-direction" "column"
                , HA.style "gap" "20px"
                , HA.style "width" "200px"
                , HA.style "flex-grow" "1"
                ]
                (Html.h1 [] [ Html.text "Explanation" ] :: description)
            ]
        ]
